// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkzkuGLhqWq6U9s-QDYutQM2iKR-T2-fo',
    appId: '1:801993737445:web:a50713ede22e362747000c',
    messagingSenderId: '801993737445',
    projectId: 'sosapp-21c4f',
    authDomain: 'sosapp-21c4f.firebaseapp.com',
    storageBucket: 'sosapp-21c4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBNBDLM-ULDnsqJYVaqL7TxwaF7gbbfk',
    appId: '1:801993737445:android:440f1054f1238a7247000c',
    messagingSenderId: '801993737445',
    projectId: 'sosapp-21c4f',
    storageBucket: 'sosapp-21c4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4BCMmiihW6oScei5JcJB0RSvgVZHqog',
    appId: '1:801993737445:ios:1270663ef45d625247000c',
    messagingSenderId: '801993737445',
    projectId: 'sosapp-21c4f',
    storageBucket: 'sosapp-21c4f.appspot.com',
    iosBundleId: 'com.example.kahoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4BCMmiihW6oScei5JcJB0RSvgVZHqog',
    appId: '1:801993737445:ios:1270663ef45d625247000c',
    messagingSenderId: '801993737445',
    projectId: 'sosapp-21c4f',
    storageBucket: 'sosapp-21c4f.appspot.com',
    iosBundleId: 'com.example.kahoot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkzkuGLhqWq6U9s-QDYutQM2iKR-T2-fo',
    appId: '1:801993737445:web:ef8525eb59372c2147000c',
    messagingSenderId: '801993737445',
    projectId: 'sosapp-21c4f',
    authDomain: 'sosapp-21c4f.firebaseapp.com',
    storageBucket: 'sosapp-21c4f.appspot.com',
  );
}
